### ISSUE TITLE
Nonstandard RSA key length

### ISSUE THREAD

**Issue by Algebra970** [sonatype-nexus-community/docker-nginx-nexus-repository#1]
https://github.com/sonatype-nexus-community/docker-nginx-nexus-repository/blob/3345bfe44cfd794208c126b2190725e627f2a010/nginx/Dockerfile#L21

The RSA key generated is **4086** bits long instead of the more standard **4096**

**Comment by whyjustin** [comment]
Thanks. PRs welcome as well. Cheers.
